theme: jekyll-theme-minimal
title: Homepage of the Salerno Automated Reasoning Lab
description: This is the website of the AureaLab, a research gorup on automated reasoning at the University of Salerno.
